name: Finnian Sturdy
favicon: null
layout_spectrum: 0.9706730784382671
typography_spectrum: 0.2579679596237838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3775887086521834
  lightness: 0.8155734669417143
  saturation: 0.7771797988098115
  rhythmicContrast: 0.7059056384023279
purpose: []
